/// The parser handles the task of converting commands passed to the repl
/// into something that can be used by it to understand and put into
/// operational use with the storage engine.
pub mod parser;

/// Interfaces to operate on the Storage Engine.
/// 1. code pertaining to environment management of a REPL.
pub mod repl;
/// 2. code pertaining to environment management of a network server.
pub mod server;

/// Code related to the heart of a database, the storage engine.
pub mod store;

/// Defines an experimental LSMT based persistant storage API.
pub mod lsmt;

/// Defines available persistant storage configurations.
pub mod config;

/// Code generated by tonic for gRPC.
pub mod kvdb_proto {
    tonic::include_proto!("kvdb");
}
